openapi: 3.0.1
info:
  title: "RESTful API for DSCensor Directed Graph"
  version: 0.0.1
servers:
  - url: /api
paths:
  /genus:
    get:
      summary: Get list of all Genus
      operationId: getGenus
      responses:
        "200":
          description: "SUCCESS"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /species:
    get:
      summary: Get list of all species
      operationId: getSpecies
      responses:
        "200":
          description: "SUCCESS"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
